# pyproject.toml for csv-app

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
packages = ["csv-app"]

[project]
name = "csv-app"
version = "0.0.1"
readme = "README.md"
requires_python = ">=3.11.2"
dependencies = ["reportlab>=4.4.9"]

[project.urls]
repository = "https://github.com/dangyogi/csv_app.git"

[project.scripts]
report = "report:run"
