# pyproject.toml for csv-app

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "csv-app"
version = "0.0.1"
description = "Library for using CSV files as a simple database"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11.2"
dependencies = ["reportlab>=4.4.9"]

[project.optional-dependencies]
test = [
    "pytest>=9.0.3"
]

[project.urls]
repository = "https://github.com/dangyogi/csv-app.git"

[project.scripts]
report = "csv_app.report:run"

[tool.setuptools.package-dir]
csv_app = "csv_app"

[tool.pytest.ini_options]
testpaths = ["tests"]
